services:
  mongodb-primary:
    image: mongo:6.0.3
    environment:
      - MONGO_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_data:/docker.io/mongo'
      - ./mongodb.key:/etc/mongodb.key
    command:
      [
        '--replSet',
        'mongoReplicaSet',
        '--keyFile',
        '/etc/mongodb.key',
        '--bind_ip_all',
      ]
    ports:
      - '27017:27017'

  mongodb-secondary:
    image: mongo:6.0.3
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGO_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGO_INITIAL_PRIMARY_ROOT_USERNAME=root
      - MONGO_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGO_REPLICA_SET_MODE=secondary
    ports:
      - 27018:27017
    volumes:
      - ./mongodb.key:/etc/mongodb.key
    command:
      [
        '--replSet',
        'mongoReplicaSet',
        '--keyFile',
        '/etc/mongodb.key',
        '--bind_ip_all',
      ]

  mongodb-arbiter:
    image: mongo:6.0.3
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGO_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGO_INITIAL_PRIMARY_ROOT_USERNAME=root
      - MONGO_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGO_REPLICA_SET_MODE=arbiter
    ports:
      - 27019:27017
    volumes:
      - ./mongodb.key:/etc/mongodb.key
    command:
      [
        '--replSet',
        'mongoReplicaSet',
        '--keyFile',
        '/etc/mongodb.key',
        '--bind_ip_all',
      ]
      
  mysql:
    image: mysql:8
    container_name: mysql
    # env_file:
    # - ./libs/common/src/database/.env
    command:
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    volumes:
      - mysql_dbdata:/var/lib/mysql
      - ./.etc/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    restart: always

volumes:
  mongodb_master_data:
    driver: local
  mysql_dbdata:
    driver: local
