services:
  mysql:
    image: mysql
    container_name: mysql
    command:
      # - --init-file=/data/application/init.sql
      - --default-authentication-plugin=mysql_native_password
      - --default-time-zone=+09:00
    env_file:
      - ./databases/mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./databases/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./databases/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./databases/mysql/init.sql:/data/application/init.sql
    ports:
      - '3306:3306'
    restart: always

  mongodb-primary:
    image: mongo:6.0.3
    environment:
      - MONGO_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_REPLICA_SET_MODE=primary
    volumes:
      - mongodb_master_data:/data/db
      - ./databases/mongo/mongodb.key:/etc/mongodb.key:z
    command:
      [
        '--replSet',
        'mongoReplicaSet',
        '--keyFile',
        '/etc/mongodb.key',
        '--bind_ip_all',
      ]
    ports:
      - '27017:27017'

  mongodb-secondary:
    image: mongo:6.0.3
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGO_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGO_INITIAL_PRIMARY_ROOT_USERNAME=root
      - MONGO_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGO_REPLICA_SET_MODE=secondary
    ports:
      - 27018:27017
    volumes:
      - mongodb_secondary_data:/data/db
      - ./databases/mongo/mongodb.key:/etc/mongodb.key:z
    command:
      [
        '--replSet',
        'mongoReplicaSet',
        '--keyFile',
        '/etc/mongodb.key',
        '--bind_ip_all',
      ]

  mongodb-arbiter:
    image: mongo:6.0.3
    depends_on:
      - mongodb-primary
    environment:
      - MONGO_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGO_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGO_INITIAL_PRIMARY_ROOT_USERNAME=root
      - MONGO_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGO_REPLICA_SET_MODE=arbiter
    ports:
      - 27019:27017
    volumes:
      - mongodb_arbiter_data:/data/db
      - ./databases/mongo/mongodb.key:/etc/mongodb.key:z
    command:
      [
        '--replSet',
        'mongoReplicaSet',
        '--keyFile',
        '/etc/mongodb.key',
        '--bind_ip_all',
      ]

  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - 16379:6379
    volumes:
      - redis:/data

volumes:
  mysql_data:
    driver: local
  mongodb_master_data:
    driver: local
  mongodb_secondary_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  redis:
    driver: local
