services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    ports:
      - '4000:4000'
    volumes:
      - ./apps/api:/usr/src/app/apps/api:z
      - ./libs/common:/usr/src/app/libs/common:z
    command: yarn start:dev api
    env_file:
      - ./apps/api/.env
    depends_on:
      - nats

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    volumes:
      - ./apps/auth:/usr/src/app/apps/auth:z
      - ./libs/common:/usr/src/app/libs/common:z
    command: yarn start:dev auth
    depends_on:
      # - mongodb-primary
      # - mysql
      - nats

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    volumes:
      - ./apps/payments:/usr/src/app/apps/payments/:z
      - ./libs/common:/usr/src/app/libs/common:z
    command: yarn start:dev payments
    depends_on:
      # - mongodb-primary
      # - mysql
      - nats

  posts:
    build:
      context: .
      dockerfile: ./apps/posts/Dockerfile
      target: development
    env_file:
      - ./apps/posts/.env
    depends_on:
      # - mysql
      # - mongodb-primary
      # - mongodb-secondary
      # - mongodb-arbiter
      - nats
    volumes:
      - ./apps/posts:/usr/src/app/apps/posts:z
      - ./libs/common:/usr/src/app/libs/common:z
      # - ./migrations:/usr/src/app/migrations:z

  videos:
    build:
      context: .
      dockerfile: ./apps/videos/Dockerfile
      target: development
    env_file:
      - ./apps/videos/.env
    command: yarn start:dev videos
    depends_on:
      # - mysql
      # - mongodb-primary
      # - mongodb-secondary
      # - mongodb-arbiter
      - nats
    volumes:
      - ./apps/videos:/usr/src/app/apps/videos:z
      - ./libs/common:/usr/src/app/libs/common:z
      # - ./migrations:/usr/src/app/migrations:z

  history:
    build:
      context: .
      dockerfile: ./apps/history/Dockerfile
      target: development
    env_file:
      - ./apps/history/.env
    command: yarn start:dev history
    depends_on:
      # - mysql
      # - mongodb-primary
      # - mongodb-secondary
      # - mongodb-arbiter
      - nats
    volumes:
      - ./apps/history:/usr/src/app/apps/history:z
      - ./libs/common:/usr/src/app/libs/common:z
      # - ./migrations:/usr/src/app/migrations:z

  storage:
    build:
      context: .
      dockerfile: ./apps/storage/Dockerfile
      target: development
    env_file:
      - ./apps/storage/.env
    command: yarn start:dev storage
    depends_on:
      # - mysql
      # - mongodb-primary
      # - mongodb-secondary
      # - mongodb-arbiter
      - nats
    volumes:
      - ./apps/storage:/usr/src/app/apps/storage:z
      - ./libs/common:/usr/src/app/libs/common:z
      # - ./migrations:/usr/src/app/migrations:z

  nats:
    image: nats:latest
    ports:
      - '4222:4222'
      - '8222:8222'
      - '6222:6222'
